on: [push]
name: AzurePowerShell
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.3
      id: script
      with:
        script: |
          apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev
          #Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          Install-Module -Name ImportExcel -Scope CurrentUser -Repository PSGallery -Force
          #Install-Module -Name Invoke-WebRequest -Scope CurrentUser -Repository PSGallery -Force
          #$a = Import-Excel https://raw.githubusercontent.com/sanket43/DemoSecretDeploy/main/.github/workflows/demo1.xlsx
          #$webRequest = Invoke-WebRequest https://raw.githubusercontent.com/sanket43/DemoSecretDeploy/main/.github/workflows/demo1.xlsx?token=GHSAT0AAAAAAB5ESCFWYKVDJMDERH4HRCBSY5YBFHA
          #$paths = ConvertFrom-StringData -StringData $webRequest.Content
          $a = $Excel.Workbooks.Open("https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fraw.githubusercontent.com%2Fsanket43%2FDemoSecretDeploy%2Fmain%2Fdemo12.xlsx&wdOrigin=BROWSELINK")
