on: [push]
name: AzurePowerShell
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.3
      id: script
      with:
        script: |
          apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev
          #Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          Install-Module -Name ImportExcel -Scope CurrentUser -Repository PSGallery -Force
          #Install-Module -Name Invoke-WebRequest -Scope CurrentUser -Repository PSGallery -Force
          $a = Import-Excel https://nacollab-my.sharepoint.com/personal/sanketm_nealanalytics_com/Documents/demo.xlsx
          #$webRequest = Invoke-WebRequest https://raw.githubusercontent.com/sanket43/DemoSecretDeploy/main/.github/workflows/demo1.xlsx?token=GHSAT0AAAAAAB5ESCFWYKVDJMDERH4HRCBSY5YBFHA
          #$paths = ConvertFrom-StringData -StringData $webRequest.Content
          #$a = $Excel.Workbooks.Open("https://nacollab-my.sharepoint.com/personal/sanketm_nealanalytics_com/Documents/demo.xlsx")
          #$Excel = New-Object -ComObject Excel.Application
          #$Workbook = $Excel.Workbooks.Open("https://nacollab-my.sharepoint.com/personal/sanketm_nealanalytics_com/Documents/demo.xlsx")
          
          
          
          $SiteUrl = "https://nacollab-my.sharepoint.com/:x:/r"
          
          $FileURL = "https://nacollab-my.sharepoint.com/:x:/r/personal/sanketm_nealanalytics_com/_layouts/15/Doc.aspx?sourcedoc=%7B907345A4-FC7A-4040-9321-96C64D2EE5EB%7D&file=demo.xlsx&action=default&mobileredirect=true"
          
          #Get Credentials to connect
          $Cred = Get-Credential

          #Set up the context
          $Ctx = New-Object Microsoft.SharePoint.Client.ClientContext($SiteUrl)
          $Ctx.Credentials = New-Object Microsoft.SharePoint.Client.SharePointOnlineCredentials($Cred.UserName,$Cred.Password)

          #powershell sharepoint online get file by url
          $File = $Ctx.web.GetFileByUrl($FileURL)
          $Ctx.Load($File)

