on: [push]
name: AzurePowerShell
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.3
      id: script
      with:
        script: |
          apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev
          #Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          Install-Module -Name ImportExcel -Scope CurrentUser -Repository PSGallery -Force
          $filepath = ".github/workflows/demo1.xlsx"
          $WorkBook = Import-Excel -Path $filepath
